name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # 你的主分支名，根据实际情况修改
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # 拉取Hugo主题子模块
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true  # 需要扩展版本支持Sass等功能

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        run: hugo --minify --gc --config .github/config.toml  # 构建并压缩静态资源，指定配置文件路径

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
